apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-app
  namespace: vnp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
