kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-home
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-share
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath
