apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-redis
  namespace: vnp
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/server/redis"
