apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: vnp
spec:
  selector:
    app: redis
  type: NodePort
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
      nodePort: 30379
